Document: wolf3d
Title: Debian wolf3d Manual
Author: <insert document author here>
Abstract: This manual describes what wolf3d is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wolf3d/wolf3d.sgml.gz

Format: postscript
Files: /usr/share/doc/wolf3d/wolf3d.ps.gz

Format: text
Files: /usr/share/doc/wolf3d/wolf3d.text.gz

Format: HTML
Index: /usr/share/doc/wolf3d/html/index.html
Files: /usr/share/doc/wolf3d/html/*.html

  
